[package]
name = "ved"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
itertools = "0.13.0"
stringreader = "0.1.1"
tempfile = "3.14.0"
thiserror = "1.0.67"
rand = "0.9.1"
glob = "0.3.3"
par-map = "0.1.4"
